### ISSUE TITLE
JavaFX - Exception in Application start method

### ISSUE THREAD

**Issue by ghost** [beryx-gist/badass-runtime-example-javafx#41]
Stack trace:

    Exception in Application start method
    java.lang.reflect.InvocationTargetException
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
    	at com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
    Caused by: java.lang.RuntimeException: Exception in Application start method
    	at com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
    	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$147(Unknown Source)
    	at com.sun.javafx.application.LauncherImpl$$Lambda$48/1732398722.run(Unknown Source)
    	at java.lang.Thread.run(Unknown Source)
    Caused by: java.lang.NullPointerException: Location is required.
    	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
    	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
    	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
    	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
    	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
    	at javafx.fxml.FXMLLoader.load(Unknown Source)
    	at application.Main.start(Main.java:14)
    	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$153(Unknown Source)
    	at com.sun.javafx.application.LauncherImpl$$Lambda$51/1778973910.run(Unknown Source)
    	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$166(Unknown Source)
    	at com.sun.javafx.application.PlatformImpl$$Lambda$44/1051754451.run(Unknown Source)
    	at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source)
    	at com.sun.javafx.application.PlatformImpl$$Lambda$47/813155481.run(Unknown Source)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source)
    	at com.sun.javafx.application.PlatformImpl$$Lambda$46/1775282465.run(Unknown Source)
    	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
    	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    	at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source)
    	at com.sun.glass.ui.win.WinApplication$$Lambda$37/1109371569.run(Unknown Source)
    	... 1 more
    Exception running application application.Main

How can I solve this issue ?

**Comment by Srijan-Sengupta** [comment]
Please show your source code I suspect you have `Caused by: java.lang.NullPointerException: Location is required.`according to the log which means you have caught null pointer error....

**Comment by AienWharlts** [comment]
> Please show your source code I suspect you have `Caused by: java.lang.NullPointerException: Location is required.`according to the log which means you have caught null pointer error....

could you help me?i meet the same problem.
